### ISSUE TITLE
[bug] Cannot disconnect from Exodus extention

### ISSUE THREAD

**Issue by slavaborovsky** [reown-com/appkit#2631]
### Link to minimal reproducible example

https://lab.web3modal.com/library/ethers/

### Summary

I connected using the Exodus extension. On clicking the disconnect button, the web3modal is stuck at the infinite loader.

Note that when I close the modal manually while loading is present, it seems that the wallet has been disconnected.

[Screencast from 07-31-2024 11:56:34 AM.webm](https://github.com/user-attachments/assets/6e613dfd-cc75-4a72-bbd4-be060507230f)

### List of related npm package versions

@web3modal/ethers": "5.0.10",
"ethers": "6.13.2",

**Comment by yashtekavade** [comment]
Hi! I was going through your query and noticed the issue you’re experiencing with the web3modal getting stuck at an infinite loader when using the Exodus extension. It seems like this might be related to your specific setup rather than a bug in the code. Here are a few steps you can try to troubleshoot and hopefully resolve the issue:

Reinstall Exodus Extension:

Sometimes, extensions can have issues. Try uninstalling the Exodus extension and then reinstalling it. After reinstalling, give it another try with the [minimal reproducible example] (https://lab.web3modal.com/library/ethers/).
Clear Browser Cache:

Old cache data can sometimes cause unexpected issues. Clear your browser cache and cookies, then refresh the page and try the connection process again.
Update Browser and Extension:

Make sure both your browser and the Exodus extension are up to date. Outdated software can lead to compatibility issues. Check for updates and install any available.
Try a Different Browser:

If the problem persists, try using a different browser to see if the issue is specific to your current one. This can help isolate whether the problem is with the browser or the extension.
If these steps don’t resolve the issue, please provide more details about your setup, such as your browser version, operating system, and any console errors you’re seeing. This information can help us further assist you.

I hope this helps! If you have any more questions or need further assistance, feel free to reach out.

**Comment by slavaborovsky** [comment]
@yashtekavade I tried with a re-installed [Exodus](https://www.exodus.com/web3-wallet/) extension in Chrome and did a fresh install in another browser (Brave). Surprisingly, I couldn't even connect in both browsers - nothing happened, and no console logs when I clicked `Connect` at [minimal reproducible example](https://lab.web3modal.com/library/ethers/). Could you confirm it worked for you when you tried the extension?

**Comment by rtomas** [comment]
hi all ! 
I cannot connect in Exodus with ethers in latest version

**Comment by rtomas** [comment]
https://linear.app/walletconnect/issue/APKT-994/[bug]-cannot-connect-from-exodus-extension

**Comment by rtomas** [comment]
Now is working in latest
