### ISSUE TITLE
[bug] `useAppKitProvider` returning `walletProvider` as `undefined` when a solana wallet is connected

### ISSUE THREAD

**Issue by DaveTheFrontEndDev** [reown-com/appkit#3043]
### Link to minimal reproducible example

https://github.com/DaveTheFrontEndDev/reown-solana-transaction-bug

### Scenario
Using the React reown libraries in a simple vite setup, implementing the `wagmi+solana` multichain setup 

Documented in the example [here](https://docs.reown.com/appkit/react/core/multichain)

### Expected Behavior
`useAppKitProvider` hook should return a `walletProvider` value as documented [here (smart contract interaction section)](https://docs.reown.com/appkit/react/core/installation?platform=solana). This example expect the walletProveder to contain a `publicKey` property.

### What is Actually Happening
`walletProvider` is being returned as undefined despite a solana wallet being connected.

### Producing the Bug
Simple Vite React app example
**Bug 1 in repo**

1) Copy `.env.example` into new file `.env` and replace with project id from [here](https://cloud.walletconnect.com/sign-in)

2) Run code example:
```
yarn install && yarn dev
```

### Example preview
https://github.com/user-attachments/assets/525c0a5a-3ee5-42d7-8d4a-d3154893d339

### List of related npm package versions

@reown/appkit: ^1.0.6
@reown/appkit-adapter-solana: ^1.0.7
@reown/appkit-adapter-wagmi: ^1.0.6
@reown/appkit-solana: ^1.0.6
@solana/wallet-adapter-wallets: ^0.19.32
@solana/web3.js: ^1.95.3
@tanstack/react-query: ^5.59.2
viem: ^2.21.15
react: ^18.2.0
wagmi: ^2.12.16

**Comment by rtomas** [comment]
Please check this example -> https://github.com/reown-com/web-examples/blob/feat/create-appkit-examples/dapps/appkit/react-solana/src/components/hooks.tsx

**Comment by DaveTheFrontEndDev** [comment]
> Please check this example -> https://github.com/reown-com/web-examples/blob/feat/create-appkit-examples/dapps/appkit/react-solana/src/components/hooks.tsx

This is now a dead link, but was able to find the example here https://github.com/reown-com/web-examples/blob/main/dapps/appkit/react-solana/src/components/hooks.tsx and it worked now

**Comment by YuryElizarov** [comment]
I am experiencing an issue with the Solana adapter where `walletProvider` becomes `undefined` after page reload, even though `window.solana` is present. 

Steps to reproduce:
1. Connect Phantom wallet via the modal.
2. Reload the page.
3. `useAppKitProvider("solana")` returns `walletProvider: undefined`.

Expected behavior:
- `walletProvider` should persist after reload, similar to EVM adapters with `enableReconnect`.

Actual behavior:
- `walletProvider` is undefined.
- Silent reconnect using `solanaWeb3JsAdapter.connect()` fails with "Provider not found".

Version:
- @reown/appkit-adapter-solana 1.7.17
