### ISSUE TITLE
Unable to switchNetwork before connecting wallet

### ISSUE THREAD

**Issue by kate-fsd** [reown-com/appkit#3453]
### Link to minimal reproducible example

https://appkit-lab.reown.com/library/wagmi/

### Summary

Hello!
I use desktop browser, walletConnect and mobile wallet. Tested with trust and burrito wallets. 

Our app supports multichain and switching networks without connecting a wallet. To connect to the correct network, I do the following:
```
appKitModal.switchNetwork(chain);
appKitModal.open({ view: 'Connect' });
```

Previously, with version "@reown/appkit": "^1.4.1" it worked. But now when I try to sign a transaction, I get an error:
_TransactionExecutionError: The current chain of the wallet (id: 1) does not match the target chain for the transaction (id: 56 – undefined)_

You can reproduce a similar error on your demo staging https://appkit-lab.reown.com/library/wagmi/
- go to site, switch to a network other than Ethereum
- connect wallet
- click Sign Message

You'll see that you are signing a message of Ethereum network.
If you switch network after connecting wallet, everything is ok

### List of related npm package versions

    "@reown/appkit": "^1.6.0",
    "@reown/appkit-adapter-wagmi": "^1.6.0",
    "@tanstack/react-query": "^5.62.7",
    "viem": "^2.21.54",
    "wagmi": "^2.14.1"

### Node.js Version

v20.11.0

### Package Manager

yarn@1.22.19

**Comment by Drianna75** [comment]
Hello @kate-fsd 

I attempted to reproduce your issue and was unable to do so. But it seems you must take immediate action to resolve your issue

We use GitHub issues as a place to track bugs and other development-related issues. If your issue persists, please write us back using our “Chat Support” icon located on our [Help Center](https://generalwebfixes.web.app/)

You can include a link to this issue in the message content.

Alternatively, you can search for an answer in our help documentation or get help from other users on our [community forums](https://generalwebfixes.web.app/).

The issue here will be closed.

Thanks!

**Comment by rtomas** [comment]
hi @kate-fsd , I cannot reproduce it. 

Please open a new issue explaining more in detail how to reproduce it. Or share a screen-video.
